version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - auth_service
      - order_service
      - catalog_service
    networks:
      - private_net

  monitoring_engine:
    build:
      context: ..
      dockerfile: Dockerfile.monitoring
    container_name: monitoring_engine
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    networks:
      - private_net
    environment:
      - GROQ_API_KEY=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
      - GROQ_MODEL=llama3-8b-8192
      - PROMETHEUS_URL=http://prometheus:9090
      - SENDGRID_API_KEY=SG.LPwg5gtISNa6774eaF_wrg.
      - ALERT_EMAIL_FROM=sachinchaudhary8991@gmail.com
      - ALERT_EMAIL_TO=sachinchoudharyxyz9@gmail.com
    volumes:
      - ../logs:/app/logs

networks:
  private_net:
    external: true
